config/routes.rb
Ej::Application.routes.draw do
  # root to: "static_pages#splash"


  get "static_pages/splash"

  get "static_pages/account"

  get "static_pages/concierge"

  #get "static_pages/contact_us"

  get "static_pages/detail"

  get "static_pages/home"

  get "static_pages/listing"

  get "static_pages/queue"

  get "static_pages/signup"

  get "admin_pages/model"
  get "admin_pages/model_removal_error"
  get "admin_pages/model_add_vendor"
  get "admin_pages/model_edit_vendor"
  get "admin_pages/model_add_photo"
  get "admin_pages/inventory"
  get "admin_pages/inventory_transit_to_member"
  get "admin_pages/inventory_available"
  get "admin_pages/inventory_full"
  get "admin_pages/inventory_arrange_transit"
  get "admin_pages/inventory_past_due"
  get "admin_pages/inventory_purchase_request"
  get "admin_pages/inventory_watch_record"
  get "admin_pages/members"
  get "admin_pages/member_individual"

  match '/ipn' => 'ipn#index'
  post '/admin/members/approval'
  resources :fedex_transits
  resources :events
  resources :news

  namespace :admin do
    post 'add_banner_photo' => 'products#add_banner_photo'
    post 'signin' => 'login#signin'
    match 'login' => 'login#index'
    match 'products/add_product' => 'products#add_product'
    match 'search_prospect' => 'members#search_prospect'
    match 'prospect_invitation' => 'members#prospect_invitation', :as => :prospect_invitation
    match 'prospects' => 'members#prospects'
    match 'page_members' => 'members#page_members'
    match 'page_member_que' => 'members#page_member_que'
    match 'page_member_rotation_history' => 'members#page_member_rotation_history'
    match "products/:product_id/upload_image" => "products#upload_image"
    match "products/add_vendor" => "products#add_vendor"
    match "products/:id/add_inventory" => "products#add_inventory"
    match "products/add_option" => "products#add_option"
    match 'products/reorder_images' => 'products#reorder_images'
    match "selection/get_pairs" => "selection#get_pairs"
    match "selection/distribute" => "selection#distribute"
    #match "products" => redirect("/admin/products/")
    match 'inventory/remove_record' => 'inventory#remove_record'
    match 'inventory/add_service/:id' => 'inventory#add_service'
    match 'inventory/status/:id' => 'inventory#status'
    match 'inventory/change_transit/:id' => 'inventory#change_transit'
    match 'admins/add_role' => 'admins#add_role'
    match 'admins/remove_role' => 'admins#remove_role'
    match 'shipping/pickup' => 'shipping#pickup'
    match 'shipping/cancel_pickup' => 'shipping#cancel_pickup'
    match 'shipping/mark_delivered' => 'shipping#mark_delivered'
    ['inventory','products', 'shipping', 'selection'].each do |path|
      controller = ('Admin::'+path.capitalize+'Controller').constantize
      controller.tabs.each do |a, l|
        action = a.to_s
        match path+'/'+action => path+"#"+action
      end
    end

    resources :products, :users, :settings, :vendors, :tiers, :courier_transits,
              :records, :product_images, :events, :inventory, :selection, :storage_records, :services,
              :rotations, :admins, :shipping, :members, :news

  end


  match "/request_product" => 'users#request_product'
  delete "/delete_request" => 'users#delete_request'
  match "/fedex-email-notifications" => 'fedex_transits#update'
  root :to => "home#home_index"
  devise_for :users, :controllers => {:registrations => "registrations"} do
    match '/auth/sign_out' => 'registrations#destroy_session', :as => :destroy_user_session
    post '/users/sign_in' => 'sessions#create'
  end

  get '/home' => 'home#home_index', :as => :home
  get 'collection/:id' => 'products#show', :as => :show_collection
  get 'collection' => 'home#collection'
  post 'comment' => 'products#comment', :as => :add_comment
  post 'comment_helpful' => 'products#comment_helpful'
  post 'filter_collection' => 'home#filter_collection'
  get 'user_queue' => 'home#user_queue'

  get '/service_benefits' => 'home#service_benefits', :as => :service_benefits

  get '/contact' => 'home#contact', :as => :contact
  post '/save_contact' => 'home#save_contact', :as => :save_contact
  get 'my_account' => 'users#my_account', :as => :my_account
  put 'update_account' => 'users#update_account', :as => :update_account
  post 'add_referral' => 'users#add_referral', :as => :add_referral
  post 'add_shipping_address' => 'users#add_shipping_address', :as => :add_shipping_address
  post 'selected_shipping' => 'users#selected_shipping', :as => :selected_shipping
  post 'rental_months' => 'users#rental_months', :as => :rental_months
  match '*path' => redirect("/users/sign_in")
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :address1, :address2, :city, :description, :drop_off, :pickup, :state, :subhead, :title, :venue, :zip,
                  :date, :start_time, :end_time, :image, :status, :rsvp


  validates :title, presence: true

  has_attached_file :image, :styles => {
      :thumb => '100x100#',
      :square => '200x200#',
      :public => '359x293#'
  }

  scope :published, where(:status => 'publish')

  def self.recently_upcoming
    where("date > ?", Time.now).order("date ASC").first
  end

end

app/controllers/admin/events_controller.rb
class Admin::EventsController < AdminController

  layout 'admin'
  #authentication before filter is in admin controller

  def index
    @events = Event.all()
  end

  def new
    if params[:copy_id]
      @existing = Event.find(params[:copy_id])
      @event = @existing.clone
    else
      @event = Event.new()
    end
    render "admin/events/create_edit"
  end

  def edit
    @event = Event.find(params[:id])
    render "admin/events/create_edit"
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes params[:event]
      redirect_to admin_events_path
    else
      render "admin/events/create_edit"
    end
  end

  def create
    @event = Event.new(params[:event])
    if @event.save()
      redirect_to admin_events_path
    else
      render "admin/events/create_edit"
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to admin_events_path
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  layout 'app'

  def index
    @wrapper = "marketing"
    @events = Event.published.order("date DESC")
    @upcoming_events = Event.published.where("date > ?", Time.now).order("date DESC")
  end

  def show
    @wrapper = "marketing"
    @event = Event.find(params[:id])
  end

end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/create_edit.html.haml
= tinymce_assets
.container
  %h2
    = @event.new_record? ? "Add Event" : "Edit Event"

  = simple_form_for [:admin, @event] do |f|
    =f.input :title
    =f.input :subhead
    =f.input :description,as: 'text',  :input_html => { class: 'tinymce', :cols => 5, :rows => 20 }
    =f.input :rsvp
    =f.input :status, :as => :select, :collection => ['draft', 'publish']
    =f.input :venue
    =f.input :address1
    =f.input :address2
    =f.input :city
    =f.input :state, :as => :select, :collection => us_states
    =f.input :zip
    =f.input :date
    =f.input :start_time
    =f.input :end_time

    %br
    =f.file_field :image
    - if not @event.image_file_name.blank?
      = image_tag @event.image.url(:thumb)

    =f.input :pickup
    =f.input :drop_off
    =f.button :submit

app/views/admin/events/index.html.haml
.container
  %h2
    Events

  = link_to 'Add New Event', new_admin_event_path

  .content.photo-list
    .table-view
      %table.ej-table{cellpadding: "5px"}
        %tr
          %td{style: "width: 200px;"}
            Title
          %td{style: "width: 200px;"}
            Date
          %td{style: "width: 400px;"}
            Address
          %td{style: "width: 400px;"}

        -@events.each do |event|
          %tr
            %td
              = link_to event.title, edit_admin_event_path(event.id)
            %td
              = event.date
            %td
              - address = [event.address1, event.address2, event.city, event.state]
              -  address.reject! { |c| c.empty? }
              = address.join(", ")
            %td
              = link_to 'delete', admin_event_path(event), :method => :delete, confirm: 'Are you sure you want to delete?'