config/routes.rb
Ej::Application.routes.draw do
  # root to: "static_pages#splash"


  get "static_pages/splash"

  get "static_pages/account"

  get "static_pages/concierge"

  #get "static_pages/contact_us"

  get "static_pages/detail"

  get "static_pages/home"

  get "static_pages/listing"

  get "static_pages/queue"

  get "static_pages/signup"

  get "admin_pages/model"
  get "admin_pages/model_removal_error"
  get "admin_pages/model_add_vendor"
  get "admin_pages/model_edit_vendor"
  get "admin_pages/model_add_photo"
  get "admin_pages/inventory"
  get "admin_pages/inventory_transit_to_member"
  get "admin_pages/inventory_available"
  get "admin_pages/inventory_full"
  get "admin_pages/inventory_arrange_transit"
  get "admin_pages/inventory_past_due"
  get "admin_pages/inventory_purchase_request"
  get "admin_pages/inventory_watch_record"
  get "admin_pages/members"
  get "admin_pages/member_individual"

  match '/ipn' => 'ipn#index'
  post '/admin/members/approval'
  resources :fedex_transits
  resources :events
  resources :news

  namespace :admin do
    post 'add_banner_photo' => 'products#add_banner_photo'
    post 'signin' => 'login#signin'
    match 'login' => 'login#index'
    match 'products/add_product' => 'products#add_product'
    match 'search_prospect' => 'members#search_prospect'
    match 'prospect_invitation' => 'members#prospect_invitation', :as => :prospect_invitation
    match 'prospects' => 'members#prospects'
    match 'page_members' => 'members#page_members'
    match 'page_member_que' => 'members#page_member_que'
    match 'page_member_rotation_history' => 'members#page_member_rotation_history'
    match "products/:product_id/upload_image" => "products#upload_image"
    match "products/add_vendor" => "products#add_vendor"
    match "products/:id/add_inventory" => "products#add_inventory"
    match "products/add_option" => "products#add_option"
    match 'products/reorder_images' => 'products#reorder_images'
    match "selection/get_pairs" => "selection#get_pairs"
    match "selection/distribute" => "selection#distribute"
    #match "products" => redirect("/admin/products/")
    match 'inventory/remove_record' => 'inventory#remove_record'
    match 'inventory/add_service/:id' => 'inventory#add_service'
    match 'inventory/status/:id' => 'inventory#status'
    match 'inventory/change_transit/:id' => 'inventory#change_transit'
    match 'admins/add_role' => 'admins#add_role'
    match 'admins/remove_role' => 'admins#remove_role'
    match 'shipping/pickup' => 'shipping#pickup'
    match 'shipping/cancel_pickup' => 'shipping#cancel_pickup'
    match 'shipping/mark_delivered' => 'shipping#mark_delivered'
    ['inventory','products', 'shipping', 'selection'].each do |path|
      controller = ('Admin::'+path.capitalize+'Controller').constantize
      controller.tabs.each do |a, l|
        action = a.to_s
        match path+'/'+action => path+"#"+action
      end
    end

    resources :products, :users, :settings, :vendors, :tiers, :courier_transits,
              :records, :product_images, :events, :inventory, :selection, :storage_records, :services,
              :rotations, :admins, :shipping, :members, :news

  end


  match "/request_product" => 'users#request_product'
  delete "/delete_request" => 'users#delete_request'
  match "/fedex-email-notifications" => 'fedex_transits#update'
  root :to => "home#home_index"
  devise_for :users, :controllers => {:registrations => "registrations"} do
    match '/auth/sign_out' => 'registrations#destroy_session', :as => :destroy_user_session
    post '/users/sign_in' => 'sessions#create'
  end

  get '/home' => 'home#home_index', :as => :home
  get 'collection/:id' => 'products#show', :as => :show_collection
  get 'collection' => 'home#collection'
  post 'comment' => 'products#comment', :as => :add_comment
  post 'comment_helpful' => 'products#comment_helpful'
  post 'filter_collection' => 'home#filter_collection'
  get 'user_queue' => 'home#user_queue'

  get '/service_benefits' => 'home#service_benefits', :as => :service_benefits

  get '/contact' => 'home#contact', :as => :contact
  post '/save_contact' => 'home#save_contact', :as => :save_contact
  get 'my_account' => 'users#my_account', :as => :my_account
  put 'update_account' => 'users#update_account', :as => :update_account
  post 'add_referral' => 'users#add_referral', :as => :add_referral
  post 'add_shipping_address' => 'users#add_shipping_address', :as => :add_shipping_address
  post 'selected_shipping' => 'users#selected_shipping', :as => :selected_shipping
  post 'rental_months' => 'users#rental_months', :as => :rental_months
  match '*path' => redirect("/users/sign_in")
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  layout :determine_layout

  def index
    @users = User.all
  end

  def collection
    @wrapper = "listing"
    @products = Product.where("quantity > ?", 0)
    if current_user
      @requested_product_ids = ProductRequest.where("user_id = ?", current_user.id).collect(&:product_id)
    end
    @requested_product_ids ||= []
  end

  def filter_collection
    @products = Product.where("quantity > ?", 0)

    @products = @products.where("LOWER(brand) ilike ?", params[:brand].downcase.strip) if params[:brand].present?
    @products = @products.where("LOWER(tier) ilike ?", params[:tier].downcase.strip) if params[:tier].present?
    @products = @products.where("LOWER(style) ilike ?", params[:type].downcase.strip) if params[:type].present?
    @products = @products.where("LOWER(face) ilike ?", params[:face].downcase.strip) if params[:face].present?
    #@products.where("brand = ?", params[:brand]) if params[:width].present?

    @requested_product_ids = ProductRequest.where("user_id = ?", current_user.id).collect(&:product_id)
    render layout: false
  end

  def user_queue
    if not current_user
      redirect_to :controller => :home, :action => :collection
      return false
    end
    @wrapper = "queue"
    @requested_products = ProductRequest.where("fulfillment_time IS NULL AND user_id = ?", current_user.id)
  end

  def contact
    @wrapper = "contact"
  end

  def save_contact
    @contact = Contact.new(params[:contact])
    @status = @contact.save
    render layout: false
  end

  def service_benefits
    @wrapper = "concierge"
  end

  def home_index
    @wrapper = "home"
    @new_collection = Product.newest_in_collection
    @upcoming_event = Event.recently_upcoming
    @latest_news = News.latest_news
  end

  private

  def determine_layout
    case action_name
    when 'collection', 'user_queue', 'contact', 'service_benefits'
      'app'
    when 'home_index'
      'home'
    else
      'application'
    end
  end

end

app/helpers/home_helper.rb
module HomeHelper

  def sanitize_filter_class(value)
    value.gsub(" ", "-").downcase
  end

end

app/views/home/_collection_list.slim
ul.watches.cgrid.compact
  - products.each do |product|
    - img_src = (product.product_images.first.url(:public) rescue '/assets/temp/D1.jpg')
    li.watch class="brand-#{sanitize_filter_class(product.brand)} tier-#{sanitize_filter_class(product.collection)}"
      .thumb
        = link_to image_tag(img_src), show_collection_path(product.id)
        .links
          - if requested_product_ids.include?(product.id)
            a.button.inque href="#" In Queue
          - else
            a.button.add href="#" data-product-id="#{product.id}" + Add

          = link_to 'Info', show_collection_path(product.id), class: 'button'

      .info
        p.brand=product.brand
        p.title= product.model
        //.tier1



//ul.cgrid.compact
//  - products.each do |product|
//    li
//      - img_src = (product.product_images.first.url(:public) rescue '/assets/temp/D1.jpg')
//      = link_to image_tag(img_src), show_collection_path(product.id)

//      .info
//        p.name style="height:20px;" = product.brand
//        .make
//          = product.model
//        .button-row.not-centered.css-center
//          - if requested_product_ids.include?(product.id)
//            a.button.upgrade href="#" data-product-id="#{product.id}" Upgrade
//          - else
//            a.button.add href="#" data-product-id="#{product.id}" + Add
//          = link_to 'Info', show_collection_path(product.id), class: 'button'

app/views/home/collection.slim
#collection-page-wrap.content
  h2 Timepieces
  .cgrid.compact
    .left-column
      =link_to "Reset All", "#", class: "reset-link"
      .collapsible-panels
        ul.filters

          li.filter
            .header.open Brand
            .content.checkbox-row style="display:block"
              - Product.get_options('brand').each_with_index do |brand, i|
                input type="checkbox" name="#{brand}" id="#{brand}#{i}" value="brand-#{sanitize_filter_class(brand)}"
                label.small-checkbox for="#{brand}#{i}" #{brand}

          li.filter
            .header.open Tier
            .content.checkbox-row style="display:block"
              - Product.get_options('collection').each_with_index do |tier, i|
                input type="checkbox" name="#{tier}" id="#{tier}#{i}" value="tier-#{sanitize_filter_class(tier)}"
                label.small-checkbox for="#{tier}#{i}" #{tier}

          - %w(Family SKU Reference Band).each do |criteria|
            li.filter
                .header= criteria
                .content.checkbox-row style="display:none"
                  - 2.times do |i|
                    input type="checkbox" name="#{criteria.parameterize}#{i}" id="#{criteria.parameterize}#{i}"
                    label.small-checkbox for="#{criteria.parameterize}#{i}" #{criteria} #{i}
    .right-column#listing-layout
      = render '/home/collection_list', products: @products, requested_product_ids: @requested_product_ids



/ .filters.form
/   .container
/     .cgrid.compact.row
/       label for="brand" Brand
/       .select-wrapper.brand.field
/         .value
/         .arrow.red
/         = select_tag 'brand', options_for_select(Product.get_options('brand').unshift(['Brand', '']))
/
/       label for="tier" Tier
/       .select-wrapper.tier.field
/         .value
/         .arrow.red
/         = select_tag 'tier', options_for_select(Product.get_options('collection').unshift(['Tier', '']))
/
/       label for="type" Type
/       .select-wrapper.type.field
/         .value
/         .arrow.red
/         = select_tag 'type', options_for_select(Product.get_options('dial_style').unshift(['Any', '']))
/
/       label for="band" band
/       .select-wrapper.band.field
/         .value
/         .arrow.red
/         select#band name=""
/           option value="0"  Band
/           option value="1"  Band 1
/           option value="2"  Band 2
/           option value="3"  Band 3
/       label for="face" Face
/       .select-wrapper.face.field
/         .value
/         .arrow.red
/         = select_tag 'face', options_for_select(Product.get_options('face_color').unshift(['Any', '']))
/       label for="width" Width
/       .select-wrapper.width.field
/         .value
/         .arrow.red
/         select#width name=""
/           option value="0" Width
/           option value="1" Width 1
/           option value="2" Width 2
/           option value="3" Width 3
/       a.action href="#" id="reset_collection" Reset All
/ #listing-layout
/   .listing
/     .container
/       = render '/home/collection_list', products: @products, requested_product_ids: @requested_product_ids

app/views/home/contact.slim
h2 Contact us
.content
  .container
    h3 Hello there, how can we be of service?
    .cgrid.compact
      .email
        .header
          h4 Email us
        .form
          = form_for Contact.new, url: save_contact_path, remote: true do |f|
            .row.cgrid.compact
              label for="name" Your name
              = f.text_field :name
            .row.cgrid.compact
              label for="email" Your email
              = f.text_field :email
            .row.cgrid.compact
              label for="subject" Subject
              = f.text_field :subject
            .row.cgrid.compact.textarea-row
              label for="message" Message
              = f.text_area :message, cols: 30, rows: 10

            .button-row.cgrid

              = f.submit 'Send', class: 'btn-style', style: 'margin-left: 40px'

      /! End email
      .call
        .header
          h4 Call us
        .body
          p
            | If you require immediate assistance,
            | please don’t hesitate to call us at:
          br/
          p.number (917) 555-1212
      /! End email
      .follow
        .header
          h4 Follow us
        .body
          p
            | Keep a keen eye on our social space for
            | special offers and exciting news:
          br/
          .dynamic-centered.social-media.black-version.cgrid
            ul.cgrid
              li.alpha
                a.facebook href="#facebook"
              li
                = link_to '', I18n.t('social_urls.twitter') , class: 'twitter'
              li
                a.pinterest href="#pinterest"
              li.omega
                a.instagram href="#instagram"

app/views/home/filter_collection.slim
= render '/home/collection_list', products: @products, requested_product_ids: @requested_product_ids

app/views/home/home_index.slim
#homepage-slider
  ul.slider.bjqs
    - Product.show_as_banner.each do |p|
      li
        .cgrid
          = image_tag p.banner_image.url(:banner)
          .info
            .decorated-block
              p.label New Addition
              p.name #{p.model}

              p.highlight #{p.brand}
            .button-row.cgrid
              a.button.primary.add href="#" data-product-id="#{p.id}" + Add
              = link_to 'Info', show_collection_path(p.id), class: 'button'

.more-links
  ul.cgrid.compact.container
    - if not @new_collection.blank?
      li.new
        h4.decorated-block New to the collection
        = image_tag(@new_collection.default_image(:public), size: "360x293")
        .info
          p.name #{@new_collection.brand}
          p #{@new_collection.model}
          a.button href="#" + Add

    - if not @upcoming_event.blank?
      li.upcoming
        h4.decorated-block Upcoming Event
        = image_tag(@upcoming_event.image.url(:public), size: "359x293")

        .info
          p #{@upcoming_event.title}
          p #{@upcoming_event.subhead}, #{@upcoming_event.date.strftime('%A %B %d, %Y')}
          a.button href="#" + Add

    - if not @latest_news.blank?
      li.news
        h4.decorated-block In the news
        = image_tag(@latest_news.image.url(:public), size: "359x293")
        .info
          p #{@latest_news.title}
          p #{@latest_news.date.strftime('%B, %Y')}
          = link_to 'Read', news_path(@latest_news), class: 'button'

app/views/home/index.html.haml
#sub_navigation= render_navigation
%h3 Home
- @users.each do |user|
  %p
    User: #{link_to user.name, user}

%h2 Products
%select{:id=>"page_size"}
  %option 15
  %option 50
  %option 100
%label{:for => "page_size"} Items Per Page
%div
  %span Page
  %span 1
  %span of
  %span 3

%table
  %thead
    %th Model
    %th Brand
    %th Tier
    %th
  %tbody
    %td
    %td
    %td
    %td

app/views/home/queue.slim
- if @requested_products.length < 8
  .ej-notification.error.container
    .close
    .cgrid.content
      p.text
        | In order to activate your first delivery, you’ll need to have a minimum of 8 watches in your queue.
        | Please view our collection and select #{8 - @requested_products.length} more.
      a.button.primary href="/collection" Add more watches

h2
  em Your Selections
  small
    |  /
  | current timepiece
.container.cgrid.your-selections
  .info
    p.name Rolex
    p.make Sea Dweller Stainless
    p Movement: Rolex Automatic
    p Case Width: 44mm
    p Height: 14.3mm
  .image
    img alt="" src="/assets/temp/C1.jpg"
  .button-row.cgrid
    a.button.primary href="#" Repeat
    a.button href="#" Comment
    a.button href="#" Buy
.ej-tabs data-active="1"
  .container
    ul
      li
        a href="#queue" Queue
      li
        a href="#history" History
      li
        a href="#guidelines" Guidelines
      li
        a href="#featured" Featured Queues
  #queue
    .container
      ul.ej-queue.cgrid
        - @requested_products.each_with_index do |pr, i|
          li.cgrid.compact class="#{"wrap" if i%2}"
            .image
              img alt="" src="/assets/temp/C2.jpg"
            .info
              p.name = pr.product.brand
              p.make = pr.product.model
              p Case Diameter: 39.7 mm
            .close

        - (8 - @requested_products.length).times do |i|
          li.cgrid.compact.unknown  class="#{"wrap" if i%2}"
            .image
              img alt="" src="/assets/unknown-watch.png"
            .info
              p.text To schedule your first delivery, you’ll need to have a minimum of 8 watches in your queue. Please view our collection and select more.
              a.button.the-collection href="/collection" The Collection
              .clear
  #history
    .container
      ul.list
        - 5.times do
          li
            .container.cgrid.compact
              .image
                img alt="" src="/assets/temp/G1.jpg"
              .info
                p.name BREITLING
                p.make Chronomat
                p Case Diameter: 39.7 mm
                p Worn: 03/18/13 - 05/18/13
                .button-row.cgrid.not-centered
                  a.button.alpha href="#" +Add
                  a.button href="#" Add comments
                  a.button href="#" Buy
  #guidelines
    .container
      p reminder/details of how the queue system works
  #featured
    .container
      p show examples of Founder's Queue, Blogger Queues, Celebrity Queues, etc

app/views/home/save_contact.js.erb
<%if @status%>
  alert('Thank you for contacting us. We will reply to you shortly.');
  $('#contact_name, #contact_email, #contact_subject, #contact_message').val('')
<%else%>
  alert("<%=@contact.errors.full_messages.join('\n').html_safe%>");
<%end%>

app/views/home/service_benefits.slim
h2 Concierge Services
.content
  .container
    h3 We’ll Be happy to service your other watches for you.
    p.text Un le je, et saucelet au donrai por fait et honiz de. Veuil mener quant vert qui garnier chapelet cuillir vie. Garnier de endeter mai qui seignor moi et mauvais covient, soit a li endeter. Mener deduire l'autr'ier la chief tient puis aimme les, et par quel ne prester je, et fait ai selon qu'il met bel, et cler pas au.
    .button-row.cgrid
      a.request-button.button.primary href="#" Request Concierge Services

app/views/home/user_queue.slim
- if @requested_products.length < 8
  .ej-notification.error.container
    .close
    .cgrid.content
      p.text
        | In order to activate your first delivery, you’ll need to have a minimum of 8 watches in your queue.
        | Please view our collection and select #{8 - @requested_products.length} more.
      a.button.primary href="/collection" Add more watches

h2
  em Your Selections
  small
    |  /
  | current timepiece
.container.cgrid.your-selections
  .info
    p.name Rolex
    p.make Sea Dweller Stainless
    p Movement: Rolex Automatic
    p Case Width: 44mm
    p Height: 14.3mm
  .image
    img alt="" src="/assets/temp/C1.jpg"
  .button-row.cgrid
    a.button.primary href="#" Repeat
    a.button href="#" Comment
    a.button href="#" Buy
.ej-tabs data-active="0"
  .container
    ul
      li
        a href="#queue" Queue
      li
        a href="#history" History
      li
        a href="#guidelines" Guidelines
      li
        a href="#featured" Featured Queues
  #queue
    .container
      ul.ej-queue.cgrid
        - @requested_products.each_with_index do |pr, i|
          li.cgrid.compact class="#{"wrap" if i%2}"
            .image
              - img_src = (pr.product.product_images[0].url(:square) rescue '/assets/temp/D1.jpg')
              img alt="" src="#{img_src}" style="width:146px;height:146px;"
            .info
              p.name = pr.product.brand
              p.make = pr.product.model
              p Case Diameter: #{pr.product.case_diameter}

            .close data-request-id="#{pr.id}"

        - (8 - @requested_products.length).times do |i|
          li.cgrid.compact.unknown  class="#{"wrap" if i%2}"
            .image
              img alt="" src="/assets/unknown-watch.png"
            .info
              p.text To schedule your first delivery, you’ll need to have a minimum of 8 watches in your queue. Please view our collection and select more.
              a.button.the-collection href="/collection" The Collection
              .clear
  #history
    .container
      ul.list
        - 5.times do
          li
            .container.cgrid.compact
              .image
                img alt="" src="/assets/temp/G1.jpg"
              .info
                p.name BREITLING
                p.make Chronomat
                p Case Diameter: 39.7 mm
                p Worn: 03/18/13 - 05/18/13
                .button-row.cgrid.not-centered
                  a.button.alpha href="#" +Add
                  a.button href="#" Add comments
                  a.button href="#" Buy
  #guidelines
    .container
      p reminder/details of how the queue system works
  #featured
    .container
      p show examples of Founder's Queue, Blogger Queues, Celebrity Queues, etc