config/routes.rb
Ej::Application.routes.draw do
  # root to: "static_pages#splash"


  get "static_pages/splash"

  get "static_pages/account"

  get "static_pages/concierge"

  #get "static_pages/contact_us"

  get "static_pages/detail"

  get "static_pages/home"

  get "static_pages/listing"

  get "static_pages/queue"

  get "static_pages/signup"

  get "admin_pages/model"
  get "admin_pages/model_removal_error"
  get "admin_pages/model_add_vendor"
  get "admin_pages/model_edit_vendor"
  get "admin_pages/model_add_photo"
  get "admin_pages/inventory"
  get "admin_pages/inventory_transit_to_member"
  get "admin_pages/inventory_available"
  get "admin_pages/inventory_full"
  get "admin_pages/inventory_arrange_transit"
  get "admin_pages/inventory_past_due"
  get "admin_pages/inventory_purchase_request"
  get "admin_pages/inventory_watch_record"
  get "admin_pages/members"
  get "admin_pages/member_individual"

  match '/ipn' => 'ipn#index'
  post '/admin/members/approval'
  resources :fedex_transits
  resources :events
  resources :news

  namespace :admin do
    post 'add_banner_photo' => 'products#add_banner_photo'
    post 'signin' => 'login#signin'
    match 'login' => 'login#index'
    match 'products/add_product' => 'products#add_product'
    match 'search_prospect' => 'members#search_prospect'
    match 'prospect_invitation' => 'members#prospect_invitation', :as => :prospect_invitation
    match 'prospects' => 'members#prospects'
    match 'page_members' => 'members#page_members'
    match 'page_member_que' => 'members#page_member_que'
    match 'page_member_rotation_history' => 'members#page_member_rotation_history'
    match "products/:product_id/upload_image" => "products#upload_image"
    match "products/add_vendor" => "products#add_vendor"
    match "products/:id/add_inventory" => "products#add_inventory"
    match "products/add_option" => "products#add_option"
    match 'products/reorder_images' => 'products#reorder_images'
    match "selection/get_pairs" => "selection#get_pairs"
    match "selection/distribute" => "selection#distribute"
    #match "products" => redirect("/admin/products/")
    match 'inventory/remove_record' => 'inventory#remove_record'
    match 'inventory/add_service/:id' => 'inventory#add_service'
    match 'inventory/status/:id' => 'inventory#status'
    match 'inventory/change_transit/:id' => 'inventory#change_transit'
    match 'admins/add_role' => 'admins#add_role'
    match 'admins/remove_role' => 'admins#remove_role'
    match 'shipping/pickup' => 'shipping#pickup'
    match 'shipping/cancel_pickup' => 'shipping#cancel_pickup'
    match 'shipping/mark_delivered' => 'shipping#mark_delivered'
    ['inventory','products', 'shipping', 'selection'].each do |path|
      controller = ('Admin::'+path.capitalize+'Controller').constantize
      controller.tabs.each do |a, l|
        action = a.to_s
        match path+'/'+action => path+"#"+action
      end
    end

    resources :products, :users, :settings, :vendors, :tiers, :courier_transits,
              :records, :product_images, :events, :inventory, :selection, :storage_records, :services,
              :rotations, :admins, :shipping, :members, :news

  end


  match "/request_product" => 'users#request_product'
  delete "/delete_request" => 'users#delete_request'
  match "/fedex-email-notifications" => 'fedex_transits#update'
  root :to => "home#home_index"
  devise_for :users, :controllers => {:registrations => "registrations"} do
    match '/auth/sign_out' => 'registrations#destroy_session', :as => :destroy_user_session
    post '/users/sign_in' => 'sessions#create'
  end

  get '/home' => 'home#home_index', :as => :home
  get 'collection/:id' => 'products#show', :as => :show_collection
  get 'collection' => 'home#collection'
  post 'comment' => 'products#comment', :as => :add_comment
  post 'comment_helpful' => 'products#comment_helpful'
  post 'filter_collection' => 'home#filter_collection'
  get 'user_queue' => 'home#user_queue'

  get '/service_benefits' => 'home#service_benefits', :as => :service_benefits

  get '/contact' => 'home#contact', :as => :contact
  post '/save_contact' => 'home#save_contact', :as => :save_contact
  get 'my_account' => 'users#my_account', :as => :my_account
  put 'update_account' => 'users#update_account', :as => :update_account
  post 'add_referral' => 'users#add_referral', :as => :add_referral
  post 'add_shipping_address' => 'users#add_shipping_address', :as => :add_shipping_address
  post 'selected_shipping' => 'users#selected_shipping', :as => :selected_shipping
  post 'rental_months' => 'users#rental_months', :as => :rental_months
  match '*path' => redirect("/users/sign_in")
end

app/models/product.rb
class Product < ActiveRecord::Base
  @@fields = {
      model: {},
      collection: {as: 'select', selection_coords: true},
      brand: {as: 'select', algorithm:true},
      case_diameter: {algorithm:true},
      face_color: {as:'select', input_html:{multiple:true}, algorithm:true },
      case_material: {as:'select', input_html:{multiple:true}, algorithm:true },
      band_color: {as: 'select', algorithm:true},
      band_material: {as: 'select', algorithm:true},
      band_name: {as: 'select', algorithm:true},
      reference: {},
      family: {},
      cost: {as: 'currency'},
      retail_price: {as: 'currency'},
      dial_style: {as: 'select', input_html:{multiple:true}},
      hand_color: {as: 'select', input_html:{multiple:true}},
      clasp_type: {as: 'select'},
      movement: {as: 'select'},
      power_reserve: {},
      bezel_type: {as: 'select'},
      purchase_date: {as:'dateselect'},
      vendor_id: {as: 'collection_select'},
      bucketed_classification: {as: 'select', input_html:{multiple:true}},
      water_resistance: {},
      is_used:  {},
      is_new_arrival: {},
      is_featured: {},
      is_borrowed: {},
      banner_display: {},
      return_date: {as:'dateselect'},
      description: {as: 'text'}

  }
  before_save :convert_fields
  belongs_to :vendor
  has_many :product_images, :dependent => :destroy
  has_many :product_instances, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  accepts_nested_attributes_for :product_images, :reject_if => lambda { |t| t['product_images'].nil? }
  accepts_nested_attributes_for :product_instances

  attr_accessible *@@fields.keys

  has_attached_file :banner_image, :styles => { :banner => '750x530#' }

  def convert_fields
    Product.fields.each do |attr,meta|
      val = self[attr]
      if(attr.to_s.index('is_')==0 && val.is_a?(String))
        self[attr] = val.downcase == 'true' ? true : false;
      elsif(meta[:as] == 'dateselect' && val.is_a?(String))
        self[attr] = Chronic.parse(val)
      elsif(meta[:as] == 'currency' && val.is_a?(String))
        self[attr] = Money.parse(val).to_f
      end
    end
  end

  def self.fields
    @@fields
  end

  def add_inventory
    product_id = sprintf '%05d', id
    quantity = ProductInstance.where('id ~ ?','^'+product_id).count + 1

    instance = ProductInstance.create(
        :id => "#{product_id}-#{quantity}",
        :is_available => true
    )
    product_instances << instance
    self.quantity = self.product_instances.size
    save()
    instance
  end

  def self.algorithm_fields
    Product.fields.reject{|k,v| !v[:algorithm]}.keys
  end

  def to_vector
    #need to implement support for fields with multiple values in them,
    vector = {}
    Product.algorithm_fields.each do |attr|
      val = self[attr]
      if(val && !val.to_s.empty?)
        vector[attr.to_s+'-'+val.to_s] = 1;
      end
    end
    vector['case_diameter'] = relative_case_diameter()
    return vector
  end

  def relative_case_diameter
    @@max_case_diameter ||= Product.maximum('case_diameter').to_i;
    @@min_case_diameter ||= Product.minimum('case_diameter').to_i;
    if @@max_case_diameter === @@min_case_diameter
      return 1
    end
    (case_diameter.to_i - @@min_case_diameter * 1.0) / (@@max_case_diameter - @@min_case_diameter)
  end

  def self.get_options field
    key = 'admin::product::options::'+ field.to_s
    stored = REDIS.get(key)
    if stored
      return JSON.parse(stored)
    else
      options = Product.select(field).group(field).map{ |p|
        self.multi_to_array(field, p)
      }.flatten.uniq
      options = options[0] == nil && options.size == 1 ? [] : options
      REDIS.set(key, options.to_json)
      return options
    end
  end

  def self.multi_to_array field, hash
    v = hash[field]
    field = field.to_sym
    (v.is_a?(String) && v.include?(',') && Product.fields[field] &&
        Product.fields[field.to_sym][:input_html] && Product.fields[field][:input_html][:multiple]) ?
        v.split(',') : v
  end

  def self.add_option field, option
    options = self.get_options(field)
    if(options.include?(option))
      return false
    end
    options << option
    REDIS.set('admin::product::options::'+ field.to_s, options.to_json)
  end

  def image(style= 'thumb')
    product_images.first && product_images.first.url(style)
  end

  def to_display
    self.attributes.keys.each do |k|
      self[k] = Product.multi_to_array(k, self)
    end
  end

  def self.show_as_banner
    where("banner_display = ?", true)
  end

  def self.newest_in_collection
    where("quantity > 0").order("created_at DESC").first
  end

  def default_image(type= :square)
    if product_images.length > 0
      product_images.first.url(type)
    else
      "/assets/temp/no_image.jpg"
    end
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < AdminController
  #before_filter :user_preferences
  #authentication before filter is in admin controller

  @@tabs = {
      :index => 'All Products',
      :add_product => 'Add Model',
      :featured => 'Featured',
      :new_arrivals  => 'New Arrivals',
      :popular => 'Popular'
  }
  def index
    @product_image = ProductImage.new()
    @products = Product.order('id ASC')
    if request.xhr?
      render :file => 'admin/products/products'
    end
  end
  def user_preferences
    key = 'admin::'+ (current_user.id.to_s)
    stored = REDIS.get(key)
    @admin_prefs = stored ? JSON.parse(stored) :  {}
    if params[:sort]
      params[:sort] = params[:sort] == 'tier' ? 'tier_id' : params[:sort]
      @admin_prefs['product_sort'] = params[:sort] + " " + (params[:order] == '1' ? 'ASC': 'DESC')
    end
    if params['page_size']
      @admin_prefs['page_size'] = params['page_size']
    end
    if params[:prefs]
      REDIS.set(key, @admin_prefs.to_json)
    end
    @order = @admin_prefs['product_sort'] || "model"
    @page_size = @admin_prefs['page_size'].to_i || 10;
  end

  def add_option
    Product.add_option(params[:field], params[:option])
    render :nothing => true
  end

  def products
    @products = Product.order(@order).page(params[:page]).per(@page_size)
  end

  def featured
    @products = Product.where('is_featured = true')
    render :layout => false, :file => 'admin/products/_featured'
  end
  def new_arrivals
    render :nothing => true
  end
  def popular
    prq = ProductRequest.count(:all, :group => 'product_id')
    render :json => {:ok => prq.to_a}
  end
  def edit
    @product = Product.find(params[:id])
    model_id = sprintf '%05d', params[:id]
    @product_instances = ProductInstance.where('id ~ ?','^'+model_id)
    @product_image = ProductImage.new()
    render "admin/products/create_edit"
  end
  def add_product
    @product = Product.where('model = ?', 'Untitled Model').last || Product.create({:model => 'Untitled Model'})
    @product.product_instances
    @product.to_display()
    @product_image = ProductImage.new()
    render :layout => false, :file => "admin/products/_add_model"
  end
  def update
    product = Product.find(params[:id])
    attrs = params[:product]
    attrs.each do |k,v|
      v = v.kind_of?(Array) && v.shift ? v.join(',') : v    #for some reason chosen makes the first element of the array an empty string, hence the shift
      attrs[k] = k.to_s.include?('_date') ? Chronic.parse(v) : v
    end
    if product.update_attributes(attrs)
      render :json => {:ok => true}
    else
      render :json => {:ok => false}
    end
  end
  def add_inventory
    product = Product.find(params[:id])
    instance = product.add_inventory();

    render :json => {:id=> instance.id, :quantity => product.quantity}
  end
  def upload_image
    render :json => {:something => "changed now"}
  end
  def show
    @product = Product.find(params[:id])
    @product_instances = ProductInstance.where('id ~ ?','^'+ sprintf('%05d',@product.id))
    @product_image = ProductImage.new()
    @product.to_display()
    render :layout => false, :file => "admin/products/_add_model"
  end
  def reorder_images
    a = []
    params[:order].each_with_index do |id, i|
      ProductImage.find(id).update_attribute(:rank, i)
      a << ProductImage.find(id)
    end
    render json: a
  end

  def add_banner_photo
    @product = Product.find(params[:hidden_product_id])
    @product.banner_image = params[:banner_image]
    @product.save
    render :layout => false
  end

  private
    def set_tabs
      @tabs = {
          :index => 'All Products',
          :add_product => 'Add Model',
          :featured => 'Featured',
          :new_arrivals  => 'New Arrivals',
          :popular => 'Popular'
      }
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  layout 'app'

  def show
    @wrapper = "detail"
    @product = Product.find(params[:id])
  end

  def comment
    @comment = Comment.new(params[:comment])
    @comment.user_id = current_user.id
    @comment.save
    redirect_to show_collection_path(@comment.product_id)
  end

  def comment_helpful
    ch = CommentHelp.new({ comment_id: params[:comment_id],
                           user_id: current_user.id,
                           helpful: (params[:flag] == 'true' ? true : false)
                        })
    status = ch.save
    if status
      render json: { message: "Saved"}
    else
      render json: { message: "Already marked by you"}
    end
  end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_add_model.slim
.container.cgrid
  = simple_form_for [:admin, @product] do |form|
        .left_col.alpha
          .section
            h3 Product Specifications
            .cgrid.form
              -Product.fields.each do |field, options|
                -options[:wrapper_html] = {class: 'row cgrid compact' }
                -if options[:as] == 'select'
                  -options[:collection] = Product.get_options(field)
                =form.input field, options


            .section
              h3 Banner Photo
              .content.banner-photo
                = image_tag((@product.banner_image.url(:banner) rescue '/assets/temp/no_image.jpg'), size: "100x100")
                = link_to 'Change', '#', id: 'add_banner_photo'


            .section
              h3 Product Photos
              .content.photo-list
                ul.cgrid.compact#photos
                  li.add-photo
                    label for="product_image_image" Add Photo
                  - @product.product_images.order('rank ASC').each do |image|
                    li{data-id=(image.id)}
                      img{src=(image.url('square'))}
                      .edit-bar
                        a href="#" Edit
                        .arrows
                          a.left href="#" <
                          a.right href="#" >
            .section.cgrid
              .form.button_panel.cgrid
                .buttonset.cgrid.alpha
              .button-row.not-centered.cgrid
                a.save.btn.button.primary.omega href="#" Save
        .right_col.omega
          .section
            .header.cgrid
              h3 Quantity
              .count.omega =@product.quantity || 0
            .body
              ul#model-inventory
                - @product.product_instances.each do |p|
                  li.cgrid
                    .number.alpha=p.id.to_s
                    a.edit.omega href="#"
              .button-row
                a.button.primary#add-inventory href="#" Add Inventory
div.vendor-dialog style="display:none"
  =render("vendor").squish.html_safe

= simple_form_for [:admin, @product_image], :html => {:target => "upload_iframe", :style=>"display:none"}  do |f|
                      = f.file_field :image
                      = f.input :product_id, :as => :hidden, :input_html => { :value => @product.id }

iframe{id="upload_iframe" src="/admin/product_images" width="200" height="200" style="position:absolute;top:-500px"}

= form_tag '/admin/add_banner_photo', id: 'banner_photo_form', :target => 'banner_iframe', multipart: true do |f|
  div style="height:0px;width:0px;overflow:hidden;"
    = file_field_tag :banner_image
  = hidden_field_tag :hidden_product_id, @product.id

iframe{name="banner_iframe" width="200" height="200" style="position:absolute;top:-500px"}

app/views/admin/products/_featured.slim
.container#listing-layout
        .listing
          .container
            ul.cgrid.compact
              - @products.each do |product|
                li
                  .bjqs-wrap.nav-on-bottom data-width="359" data-height="293"
                    ul.bjqs
                      -product.product_images.each do |image|
                        li
                          img{alt="" src=(image.url('public'))}

                  .info
                    p.name =product.model
                    .make
                        =product.brand
                    .item-footer
                      .button-row.cgrid
                        a.button href="#" Remove

app/views/admin/products/_index.js.erb
$('#products').html('<%=escape_javascript render(@products)%>');
$('#paginator').html('<%= escape_javascript(paginate(@products, :remote => true).to_s) %>');

app/views/admin/products/_product.html.haml
%tr
  %td
    = product.model
    %td
      = product.brand
    %td
      = link_to 'edit', edit_admin_product_path(product.id)
    %td

app/views/admin/products/_vendor.html.haml
%div
  =simple_form_for :vendor  do |f|
    =f.text_field :name, placeholder: 'name', class: "required"
    =f.text_field :address, placeholder: 'address', class: "required"
    =f.text_field :phone, placeholder: 'phone', class: "required phoneUS"
    =f.text_field :email, placeholder: 'email', class: "required email"
    =f.text_field :website, placeholder: 'website', class: "required url"
    %button{class: "cancel"}
      Cancel
    = f.submit 'Add Vendor'

app/views/admin/products/add_banner_photo.html.haml
%script{type: 'text/javascript'}
  parent.banner_photo.change_pic("#{@product.banner_image.url(:banner)}")

app/views/admin/products/add_vendor.js.erb
$('<div class="modal hide fade"><%=render("vendor").squish.html_safe -%></div>').modal({backdrop:false});


$('#add_vendor').submit(function(){
    var data = $(this).serialize();
    $.ajax({
        type: "POST",
        url: "/admin/vendors",
        data: $(this).serialize(),
        success: function(response){
            $("#product_vendor").append('<option value="'+response.id+'">'+response.name+'</option>')
                .trigger("liszt:updated")
            $('.modal').hide();
        },
        error: function(){
            alert("An unexpected error has occurred")
        },
        dataType:'json'
    });
    return false;
}).validate()

app/views/admin/products/create_edit.html.haml
= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/chosen/0.9.12/chosen.jquery.min.js"
= stylesheet_link_tag "//cdn.jsdelivr.net/chosen/0.9.11/chosen.css"
= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.11.0/jquery.validate.min.js"
= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/jquery-jcrop/0.9.12/js/jquery.Jcrop.min.js"
= stylesheet_link_tag "http://jcrop-cdn.tapmodo.com/v0.9.12/css/jquery.Jcrop.min.css"

#sub_navigation= render_navigation
HOLA!!!

= simple_form_for [:admin, @product] do |f|
  = f.input :quantity, :input_html => {:min => 0}
  = f.input :model
  = f.input :brand
  = f.input :material
  = f.input :style
  = f.input :color
  = f.input :case
  = f.input :msrp
  %label
    Vendor
  = f.collection_select "vendor_id", Vendor.all, :id, :name, :label => "Name", :input_html => {'data-placeholder' => 'eretrefw'}
  = f.input :description
  = f.button :submit

%table{:id=>'product_instances'}
  - @product_instances.each do |product_instance|
    %tr
      %td
        = product_instance.id

%button{:id=>"add-watch"} Add Watch

%div{:class=>"modal hide fade"}
  = render("vendor").squish.html_safe

%h3 Add Product Photos

= simple_form_for [:admin, @product_image], :html => {:target => "upload_iframe"}  do |f|
  = f.file_field :image
  = f.input :product_id, :as => :hidden, :input_html => { :value => @product.id }

%iframe{:id=>"upload_iframe", :src=>"/admin/product_images", :width=>"200", :height=>"200", :style => 'display:none'}

%h3
  Photos
  %ul{:id=>'photos'}
    - @product.product_images.each do |image|
      %li{'data-id' => image.id}
        %img{:src=>image.url("square")}

app/views/admin/products/index.js.erb
$('#products').html('<%=escape_javascript render(@products)%>');
$('#paginator').html('<%= escape_javascript(paginate(@products, :remote => true).to_s) %>');

app/views/admin/products/index.slim
#admin-manage-models
  h2 Manage Models
  =show_tabs()

app/views/admin/products/product_image.js.erb
$('<div class="modal hide fade"><%=render("vendor").squish.html_safe -%></div>').modal({backdrop:false});

app/views/admin/products/products.slim
/#sub_navigation= render_navigation
  %h3 Home
  %h2 Products
  %script{:src=>"//cdnjs.cloudflare.com/ajax/libs/chosen/0.9.12/chosen.jquery.min.js"}
  %link{:rel=>"stylesheet", :href => "//cdn.jsdelivr.net/chosen/0.9.11/chosen.css"}

  = simple_form_for :preference do |f|
    = f.select :page_size, [10,20,50], :selected => @admin_prefs['page_size']

  %div{:id=>"paginator"}
    = paginate @products, :remote => true



  %table

    %thead
      %th
        = link_to 'Model', admin_products_path+'?&prefs=1&sort=model&order=-1',  {:id => 'model_sort'}
      %th
        = link_to 'Brand', admin_products_path+'?&prefs=1&sort=brand&order=-1', {:id => 'brand_sort'}
      %th
        = link_to 'Tier', admin_products_path+'?&prefs=1&sort=tier&order=-1', {:id => 'tier_sort'}
      %th
    %tbody{:id=>"products"}
      = render @products

.container
        /.search-header
          /.cgrid.compact
            form
              .token-input-wrap.filter.cgrid
                label.alpha Filter
                ul.token-input-list.omega
                  - ["iwc", "Cartier", "Burberry", "Jeager"].each do |i|
                    li.token-input-token
                      p= i
                      .token-input-delete-token x
                  li.token-input-token
                    input type="text"
                .arrow
                .dropdown
                  .cgrid.select_row
                    .brands_select_field.multiple_select_field
                      select.custom_select_wrapper multiple="multiple" data-width="114" data-class="brands" data-prompt="Brand"
                        - @brands.each_with_index do |b,i|
                          option value="#{i}" #{b}
                    .tier_select_field.multiple_select_field
                      select.custom_select_wrapper multiple="multiple" data-width="114" data-class="tier" data-prompt="Tier"
                        - @tiers.each_with_index do |b,i|
                          option value="#{i}" #{b}
                    .diameter_select_field.multiple_select_field
                      select.custom_select_wrapper multiple="multiple" data-width="145" data-class="diameter" data-prompt="Case Diameter"
                        - @diameter.each_with_index do |b,i|
                          option value="#{i}" #{b}
                  .button-row.cgrid.not-centered(style="width: 196px")
                    a.button.primary href="#" Filter
                    a.button href="#" Reset All
            img.seperator src="/assets/seperator-pointed.png"
            form
              .token-input-wrap.search
                label Search
                ul.token-input-list
                  - ["Search Term A", "Search Term B"].each do |i|
                    li.token-input-token
                      p= i
                      .token-input-delete-token x
                  li.token-input-token
                    input type="text"
                .arrow
                .dropdown
                  .form
                    .row.cgrid.compact.search_for
                      label Search for
                      input type="text"
                    .buttonset.search-within-results
                      label for="search_within_results" Search within results
                      input id="search_within_results" type="checkbox"
                    .button-row
                      a.button.primary Search

            img src="/assets/seperator-pointed.png"
            .count
              p 5 items
            /img.seperator src="/assets/seperator-pointed.png"
            /a.button.export.primary href="#" Export
        /.page-controls.cgrid
          .alpha
            .select-wrapper
              .value
              .arrow.red
              select
                - 3.times do |i|
                  option value="#{(i+1)*10}" #{(i+1)*10}
            .label items per page
          .omega
            .label page
            input.ej-text-field type="text" value="1"
            .label of 5
            span.arrow
              a.prev href="#" <
              a.next.active href="#" >
        .table-view
          table.ej-table
            thead
              ruby:
                cols = [
                  {text: "Product Id", classname: "id", width: 118},
                  {text: "Brand", classname: "brand", width: 190},
                  {text: "Model", classname: "model", width: 295},
                  {text: "Case Diameter", classname: "case_diameter", width: 165},
                  {text: "Collection", classname: "collection", width: 185},
                ]
              - cols.each do |i|
                th class="#{i[:classname]}"  style="width:#{i[:width]}px;"
                  span.cgrid.compact
                    span= i[:text]
                    a.sort class="#{'active' if i[:text] == 'Tier'}" href="#"
            tbody
              - @products.each_with_index do |product, i|
                tr{class="#{'even' if i%2 == 1}" data-id=(product.id)}


                  - cols.each do |cell|
                      td class="#{cell[:classname]}" style="width:#{cell[:width]}px;"
                        - data = product.read_attribute(cell[:classname])
                        span= (cell[:classname] == 'id' ? sprintf('%05d', data) : data)
        /.page-controls.cgrid
          .alpha
            .select-wrapper
              .value
              .arrow.red
              select
                - 3.times do |i|
                  option value="#{(i+1)*10}" #{(i+1)*10}
            .label items per page
          .omega
            .label page
            input.ej-text-field type="text" value="1"
            .label of 5
            span.arrow
              a.prev href="#" <
              a.next.active href="#" >

app/views/admin/products/show.html.haml
#sub_navigation= render_navigation